# Generated by Django 5.0.3 on 2024-03-10 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=30)),
                ('colour', models.CharField(max_length=30)),
                ('details', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('la_image', models.ImageField(default='', upload_to='image')),
            ],
        ),
    ]
