# Generated by Django 5.0.3 on 2024-03-10 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('techapp', '0003_cart_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billingdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('F_name', models.CharField(max_length=30)),
                ('Email', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
